print("My Family")
name=input("Enter Your Name")
fname=input("Enter Your Father Name")
mname=input("Enter Your Mother Name")
sname=input("Enter Your Sister Name")
print(name)
print(fname)
print(mname)
print(sname)
